In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\acer\OneDrive\Desktop\day12 dataset cleaned.csv")

In [3]:
df.shape

(9994, 9)

In [4]:
df.head()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
0,CA-2016-152156,CG-12520,11-Aug-16,42420,? 731.94,FUR-CH-10000454,3,0.0,? 219.582
1,CA-2015-106320,EB-13870,25-Sep-15,84057,"? 1,044.63",FUR-TA-10000577,3,0.0,? 240.2649
2,CA-2016-121755,EH-13945,16-Jan-16,90049,? 90.57,TEC-AC-10003027,3,0.0,? 11.7741
3,CA-2016-169194,LH-16900,20-Jun-16,19901,? 45.,TEC-AC-10002167,3,0.0,? 4.95
4,CA-2015-135545,KM-16720,24-Nov-15,90004,? 146.73,OFF-PA-10003892,3,0.0,? 68.9631

In [5]:
df.tail()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
9989,CA-2016-105781,JF-15565,16-Feb-16,10024,? 326.646,FUR-CH-10001802,3,0.10,? 39.9234
9990,CA-2017-144491,CJ-12010,27-Mar-17,77070,"? 1,023.332",FUR-BO-10001811,5,0.32,30.098 -?
9991,CA-2016-122581,JK-15370,21-Aug-16,10035,? 573.174,FUR-CH-10002961,7,0.10,? 63.686
9992,CA-2015-104948,KH-16510,13-Nov-15,92404,? 683.332,FUR-BO-10004357,4,0.15,40.196 -?
9993,CA-2015-168088,CM-12655,19-Mar-15,77041,? 383.4656,FUR-BO-10004218,4,0.32,67.6704 -?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Customer ID  9994 non-null   object
 2   Order Date   9994 non-null   object
 3   Postal Code  9994 non-null   int64
 4   Sales        9994 non-null   object
 5   Product ID   9994 non-null   object
 6   Quantity     9994 non-null   int64
 7   Discount     9994 non-null   float64
 8   Profit       9994 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 702.8+ KB

In [7]:
df.describe()

        Postal Code     Quantity     Discount
count   9994.000000  9994.000000  9994.000000
mean   55190.379428     3.789574     0.156203
std    32063.693350     2.225110     0.206452
min     1040.000000     1.000000     0.000000
25%    23223.000000     2.000000     0.000000
50%    56430.500000     3.000000     0.200000
75%    90008.000000     5.000000     0.200000
max    99301.000000    14.000000     0.800000

In [8]:
#How many rows
df.shape[0]

9994

In [10]:
#How many columns
df.shape[1]

9

In [11]:
#Which columns have missing value
df.isnull().sum()

Order ID       0
Customer ID    0
Order Date     0
Postal Code    0
Sales          0
Product ID     0
Quantity       0
Discount       0
Profit         0
dtype: int64

In [17]:
#What is the average value of one numeric column
a=df["Sales"].mean()
print(a)

TypeError: Could not convert string '? 731.94? 1,044.63? 90.57? 45.? 146.73? 19.05? 16.74? 20.1? 53.34? 787.53? 47.04? 238.56? 20.04? 8.82? 10.86? 143.7? 839.43? 149.97? 6.63? 20.94? 46.26? 20.37? 221.55? 5.28? 56.91? 9.84? 45.48? 87.54? 7.56? 1,799.97? 35.91? 32.7? 194.94? 70.95? 242.94? 59.52? 161.94? 30.48? 9.84? 340.92? 40.2? 9.09? 11.07? 8.34? 46.74? 126.3? 6.63? 51.45? 1,126.02? 47.94? 152.94? 42.6? 19.44? 14.85? 8.82? 294.93? 88.02? 13.23? 392.94? 18.84? 10.74? 61.44? 99.39? 479.97? 19.44? 36.84? 209.88? 299.97? 146.82? 1,652.94? 296.37? 33.63? 242.94? 179.97? 58.05? 12.39? 50.94? 5.64? 207.? 59.94? 186.69? 332.94? 149.97? 239.97? 167.97? 180.66? 60.45? 287.94? 242.94? 34.44? 322.59? 371.97? 20.04? 85.14? 540.57? 35.97? 8.64? 501.81? 34.02? 17.97? 10.23? 617.97? 36.63? 19.44? 484.65? 155.25? 155.82? 22.74? 1,267.53? 197.97? 854.94? 31.44? 8.73? 8.64? 22.92? 6.63? 23.34? 1,067.94? 19.44? 62.31? 362.94? 53.94? 272.94? 19.44? 27.93? 179.97? 113.79? 182.94? 6.57? 32.97? 278.4? 15.48? 20.82? 32.94? 286.38? 287.97? 161.94? 46.26? 37.05? 25.11? 677.58? 47.82? 17.61? 79.14? 49.08? 1,089.75? 18.84? 104.85? 484.83? 122.97? 154.44? 251.79? 239.97? 37.74? 91.68? 91.2? 452.94? 872.94? 8.67? 33.87? 177.? 89.97? 42.6? 40.05? 34.5? 40.74? 11.67? 782.94? 5.28? 122.97? 12.84? 21.84? 170.88? 47.04? 143.7? 10.65? 13.44? 5.46? 29.79? 1,265.85? 19.44? 41.37? 1,247.64? 95.94? 104.28? 17.94? 14.82? 14.46? 7.83? 31.44? 59.97? 122.94? 86.97? 134.97? 107.94? 347.97? 90.57? 14.52? 29.34? 31.56? 34.65? 99.39? 92.94? 145.74? 14.73? 197.97? 4.92? 167.97? 16.2? 33.99? 13.71? 286.29? 281.97? 166.44? 275.97? 23.88? 17.22? 26.22? 17.34? 95.94? 17.04? 49.53? 14.73? 10.95? 269.97? 29.04? 597.? 17.31? 11.34? 12.39? 59.97? 58.2? 146.73? 26.55? 8.34? 5.04? 29.7? 19.65? 146.82? 14.94? 501.81? 161.94? 314.55? 44.4? 60.81? 65.34? 35.1? 14.67? 191.82? 19.44? 143.7? 43.26? 437.85? 371.97? 359.97? 287.97? 181.95? 12.72? 106.32? 182.94? 389.97? 94.74? 10.86? 113.97? 79.47? 5.67? 826.11? 269.49? 57.06? 46.53? 29.97? 5.46? 9.84? 20.04? 64.17? 129.93? 868.59? 173.94? 16.23? 675.12? 62.82? 19.44? 12.42? 914.97? 587.97? 14.94? 14.94? 1,349.85? 4.17? 37.32? 14.94? 64.14? 57.69? 42.81? 104.85? 164.88? 1,292.94? 10.86? 166.44? 166.44? 116.28? 19.44? 377.97? 6.63? 377.97? 299.97? 323.37? 239.97? 49.44? 154.44? 36.27? 41.37? 12.84? 214.11? 653.55? 19.44? 50.94? 2,690.97? 40.29? 377.97? 31.44? 59.52? 6.03? 254.97? 27.93? 6.63? 17.94? 35.88? 14.94? 11.22? 135.72? 18.84? 8.64? 368.97? 26.25? 20.34? 61.44? 91.68? 191.82? 5.04? 92.94? 66.69? 17.94? 83.97? 104.97? 124.41? 539.97? 166.44? 21.93? 242.94? 206.43? 31.05? 59.52? 19.35? 20.94? 826.62? 544.38? 23.34? 29.97? 149.97? 44.94? 49.08? 18.24? 241.44? 2.97? 6.54? 18.24? 15.24? 13.11? 11.91? 8.64? 68.94? 128.82? 203.52? 122.97? 59.97? 89.97? 35.28? 19.44? 28.44? 17.94? 193.95? 5.46? 29.79? 16.74? 1,202.94? 209.97? 62.94? 66.3? 404.94? 599.97? 38.97? 40.74? 83.25? 9.45? 1,577.94? 465.18? 29.34? 14.94? 377.97? 464.97? 12.39? 84.09? 9.84? 43.26? 19.14? 899.97? 162.6? 14.94? 71.97? 11.85? 368.97? 116.28? 8.52? 62.91? 29.79? 59.97? 76.14? 170.97? 501.81? 134.85? 239.97? 19.44? 57.93? 17.34? 22.14? 12.84? 44.67? 8.94? 56.52? 22.77? 512.94? 542.94? 8.64? 25.86? 479.97? 80.88? 276.69? 116.28? 10.95? 587.97? 17.34? 19.44? 37.59? 35.91? 209.97? 18.9? 8.82? 322.59? 12.84? 539.97? 671.94? 19.44? 122.97? 17.04? 344.91? 10,499.97? 21.93? 17.67? 9.42? 128.4? 9.24? 174.42? 149.97? 27.81? 66.3? 1,103.97? 129.39? 19.44? 304.23? 9.21? 107.97? 113.82? 544.38? 60.72? 29.16? 131.94? 7.41? 270.72? 60.45? 1,259.97? 68.97? 901.95? 21.24? 314.55? 19.65? 617.97? 59.7? 302.94? 27.18? 70.95? 7.98? 842.94? 186.69? 333.09? 116.28? 19.44? 314.55? 62.85? 62.31? 40.44? 15.84? 18.24? 12.84? 56.82? 271.44? 76.14? 21.24? 113.1? 5.58? 25.02? 53.97? 21.81? 535.41? 542.94? 36.63? 123.96? 242.94? 12.39? 13.62? 272.94? 302.94? 212.13? 130.71? 62.31? 8.22? 14.73? 9.87? 53.25? 19.92? 9.21? 27.93? 18.69? 25.35? 35.28? 182.94? 6.24? 8.67? 25.71? 5.64? 33.63? 17.94? 5.64? 36.63? 12.39? 12.54? 8.94? 9.24? 239.97? 344.91? 8.64? 182.67? 1,126.02? 8.82? 91.59? 173.94? 19.44? 897.15? 14.94? 18.84? 12.42? 79.14? 17.94? 242.94? 128.85? 84.84? 47.79? 17.94? 10.11? 772.47? 347.58? 772.47? 461.97? 302.67? 8.34? 212.94? 653.55? 67.71? 377.97? 123.96? 38.34? 18.24? 51.45? 34.44? 19.44? 287.97? 23.34? 1,214.85? 6.6? 212.94? 12.84? 15.84? 563.94? 62.94? 535.41? 144.12? 314.55? 45.78? 40.29? 45.66? 158.13? 70.26? 465.18? 36.63? 51.45? 7.83? 79.14? 212.94? 166.44? 54.96? 164.22? 362.94? 332.94? 43.5? 182.91? 167.94? 715.2? 36.84? 15.84? 44.4? 18.9? 296.37? 19.44? 17.34? 32.34? 306.9? 31.44? 15.54? 109.53? 10.65? 101.34? 46.53? 270.? 10.71? 357.93? 9.24? 19.44? 44.4? 17.94? 128.4? 7.83? 239.97? 128.85? 26.85? 323.37? 59.94? 64.14? 11.67? 17.43? 43.68? 14.94? 56.52? 546.06? 269.49? 34.05? 437.85? 25.02? 10.71? 234.45? 284.97? 60.84? 17.94? 19.44? 389.97? 15.84? 542.94? 11.64? 79.44? 357.93? 19.44? 5.94? 29.16? 178.11? 1,089.75? 30.69? 20.04? 44.4? 542.94? 14.91? 30.48? 18.9? 19.44? 36.6? 795.51? 74.76? 29.22? 19.44? 79.47? 127.95? 9.54? 17.94? 4,912.59? 179.97? 99.87? 44.4? 31.56? 59.94? 59.7? 14.52? 46.53? 25.5? 209.97? 299.97? 17.22? 43.02? 128.85? 127.95? 68.52? 74.94? 271.44? 19.44? 9.84? 15.24? 42.6? 5.28? 692.94? 14.67? 12.6? 17.94? 10.95? 191.82? 29.22? 104.85? 59.97? 14.94? 53.25? 115.44? 20.07? 81.54? 113.73? 70.95? 31.44? 50.97? 65.94? 18.24? 68.16? 29.97? 19.44? 166.5? 25.35? 22.14? 6.24? 200.97? 22.92? 34.5? 12.42? 428.4? 64.14? 25.83? 127.95? 579.51? 144.12? 65.97? 272.94? 43.92? 14.73? 119.85? 587.97? 37.32? 6.63? 371.97? 8.01? 102.93? 368.97? 12.39? 332.94? 19.44? 99.87? 82.26? 89.97? 20.94? 1,247.64? 34.02? 302.67? 16.14? 8.64? 8.34? 101.94? 179.97? 302.94? 14.94? 34.65? 60.72? 146.82? 5.94? 21.3? 209.88? 212.94? 6.99? 393.54? 146.82? 164.88? 47.97? 5.43? 7.83? 16.74? 10.47? 11.07? 113.76? 579.51? 17.94? 272.94? 344.94? 129.93? 62.94? 6.24? 197.97? 20.7? 11.34? 494.97? 182.94? 28.14? 254.97? 1,652.94? 146.73? 19.05? 113.94? 186.54? 28.8? 18.9? 21.93? 68.52? 146.82? 7.8? 22.32? 824.97? 30.18? 44.43? 186.54? 208.44? 146.76? 587.97? 14.94? 28.14? 92.94? 17.94? 50.22? 32.67? 99.87? 106.32? 163.44? 17.94? 10.02? 144.12? 17.94? 13.89? 257.94? 828.6? 92.94? 52.56? 21.84? 107.97? 89.97? 12.78? 30.18? 14.73? 8.82? 137.94? 22.83? 8.64? 989.97? 68.52? 364.74? 389.97? 57.69? 158.13? 14.13? 43.92? 9.45? 25.71? 19.44? 61.02? 40.74? 17.61? 17.64? 29.97? 59.52? 122.91? 11.43? 32.67? 18.9? 14.94? 276.69? 18.84? 140.97? 9.24? 29.7? 34.74? 497.94? 533.94? 167.94? 15.? 563.94? 17.94? 122.97? 122.94? 17.31? 19.44? 14.91? 7.44? 258.75? 59.52? 119.1? 59.94? 38.97? 152.94? 14.94? 3,812.97? 179.94? 872.94? 25.71? 209.97? 479.97? 8.64? 59.52? 40.74? 17.52? 12.42? 19.44? 566.97? 9.84? 60.84? 467.97? 154.95? 17.52? 6.12? 7.86? 51.45? 47.01? 7.98? 113.22? 8.64? 149.97? 59.52? 6.12? 58.05? 235.95? 166.44? 106.32? 48.72? 101.34? 174.3? 2.97? 50.97? 59.52? 540.57? 659.97? 113.73? 37.59? 45.84? 106.32? 18.84? 41.91? 17.94? 359.97? 116.82? 239.97? 27.42? 75.? 23.88? 26.85? 148.02? 535.41? 36.84? 14.73? 186.54? 20.04? 108.96? 19.44? 11.82? 89.97? 35.97? 357.? 85.44? 344.91? 46.74? 19.44? 122.94? 675.06? 7.98? 143.7? 17.94? 61.44? 186.54? 82.26? 59.97? 137.94? 901.95? 106.32? 104.28? 45.? 95.94? 17.94? 370.14? 11.94? 5.94? 59.52? 479.97? 17.52? 182.22? 302.94? 389.97? 56.4? 39.? 5.67? 7.98? 14.94? 479.97? 70.26? 12.39? 14.19? 47.79? 19.44? 344.91? 52.59? 19.44? 126.3? 535.41? 10.74? 59.94? 27.42? 5.4? 1,128.39? 34.77? 18.9? 12.72? 70.95? 299.97? 89.97? 31.05? 36.27? 34.05? 239.97? 449.97? 312.03? 17.94? 494.97? 30.84? 21.93? 29.34? 164.88? 10.95? 19.44? 89.97? 15.24? 17.64? 20.97? 37.74? 14.82? 191.82? 61.44? 479.97? 44.4? 66.03? 65.94? 89.97? 19.44? 146.73? 15.18? 125.13? 680.01? 241.44? 1,112.94? 22.92? 19.44? 15.48? 5.4? 19.44? 79.44? 11.07? 23.67? 9.84? 14.94? 332.94? 51.9? 25.5? 389.97? 20.04? 10.02? 1,577.94? 392.94? 9.84? 34.5? 146.73? 19.44? 22.14? 272.97? 31.8? 542.94? 17.94? 10.11? 45.? 12.39? 186.15? 47.19? 144.6? 34.44? 6.54? 9.12? 167.94? 26.94? 32.04? 13.89? 31.56? 1,079.85? 25.86? 60.84? 11.07? 14.67? 177.? 281.97? 97.44? 193.95? 119.94? 12.42? 71.97? 14.94? 6.99? 8.64? 22.83? 11.01? 12.39? 340.92? 89.97? 89.97? 140.67? 9.45? 332.94? 239.97? 437.85? 48.81? 34.65? 152.91? 92.94? 13.11? 14.04? 62.31? 5.94? 8.94? 44.67? 31.05? 14.91? 24.27? 164.85? 102.93? 40.74? 83.97? 261.96? 14.62? 55.5? 8.56? 77.88? 45.98? 17.46? 21.8? 6.16? 14.56? 30.? 13.98? 75.88? 301.96? 6.16? 12.96? 32.96? 41.96? 75.96? 4.02? 14.62? 110.96? 29.? 7.16? 131.98? 10.56? 166.72? 79.9? 8.82? 26.8? 3,991.98? 7.16? 24.56? 12.96? 24.56? 8.26? 20.7? 20.7? 5.56? 7.36? 41.9? 39.98? 49.96? 12.96? 28.4? 5.96? 159.98? 29.6? 93.98? 105.42? 38.04? 5.88? 11.96? 210.98? 66.26? 13.36? 1,295.78? 20.7? 3.96? 7.3? 76.12? 40.48? 9.94? 301.96? 97.16? 330.4? 209.3? 97.82? 64.96? 14.62? 307.98? 9.94? 6.3? 49.98? 24.56? 11.36? 641.96? 18.28? 40.3? 9.96? 12.96? 12.96? 18.28? 28.4? 25.78? 18.28? 9.82? 15.28? 301.96? 191.98? 11.36? 14.62? 5.16? 44.46? 39.96? 21.36? 7.16? 7.36? 23.1? 11.36? 30.84? 17.46? 64.96? 12.96? 352.38? 24.56? 28.84? 12.96? 17.12? 204.6? 6.24? 21.88? 9.82? 12.96? 44.02? 13.96? 86.62? 31.86? 11.16? 108.4? 119.96? 362.92? 355.96? 119.98? 6.3? 4.36? 15.28? 37.68? 19.98? 17.38? 204.6? 5.84? 12.76? 599.98? 3.64? 122.48? 455.1? 11.54? 109.48? 22.38? 172.5? 3.76? 197.58? 193.86? 15.28? 5.68? 2.78? 79.96? 22.96? 3.2? 69.9? 12.48? 39.88? 26.96? 61.96? 21.78? 29.78? 93.78? 31.4? 29.6? 239.98? 167.96? 11.56? 21.8? 75.48? 39.98? 13.76? 27.46? 3.68? 41.54? 12.96? 3.76? 9.64? 9.94? 8.36? 7.3? 16.28? 111.96? 171.96? 307.98? 41.96? 6.16? 211.96? 59.48? 198.46? 50.? 9.64? 12.7? 209.7? 109.92? 13.36? 2.96? 58.58? 196.62? 104.98? 106.96? 9.96? 7.42? 17.9? 13.36? 9.46? 109.92? 8.56? 35.06? 9.82? 20.86? 5.34? 6.58? 699.98? 7.38? 9.26? 9.96? 37.68? 97.82? 137.62? 10.56? 1,793.98? 14.78? 18.96? 299.9? 199.98? 23.1? 11.54? 238.? 24.18? 3.76? 13.08? 14.62? 141.96? 8.26? 14.62? 162.64? 411.8? 3.96? 5.76? 26.? 46.84? 241.96? 17.14? 45.68? 29.? 121.3? 241.96? 52.98? 190.86? 56.56? 5.56? 9.02? 13.36? 43.56? 109.48? 18.54? 499.98? 8.26? 12.96? 199.98? 23.92? 35.04? 892.98? 12.96? 14.62? 416.32? 12.96? 41.96? 10.86? 127.88? 160.32? 7.86? 39.68? 37.6? 59.9? 5.76? 11.96? 301.96? 63.56? 7.4? 33.96? 257.98? 17.48? 97.84? 5.56? 85.52? 124.46? 7.38? 12.96? 21.96? 50.? 323.1? 33.82? 11.36? 16.68? 187.98? 79.1? 180.96? 530.34? 121.94? 5.78? 39.96? 323.1? 12.96? 261.74? 79.96? 8.76? 26.2? 16.68? 129.98? 71.98? 124.36? 73.98? 89.98? 25.98? 35.34? 5.56? 11.96? 257.98? 7.9? 25.96? 39.96? 9.42? 12.96? 124.36? 7.16? 52.34? 4.66? 12.96? 51.96? 11.56? 310.12? 8.56? 12.56? 129.3? 18.96? 22.58? 19.36? 56.3? 29.16? 12.96? 22.18? 411.8? 41.96? 37.94? 517.9? 5.28? 8.96? 30.56? 114.46? 12.96? 58.34? 44.46? 13.28? 735.98? 26.? 15.56? 18.76? 58.68? 9.64? 39.88? 430.88? 99.98? 135.98? 12.96? 6.56? 11.68? 3.48? 81.98? 359.98? 20.88? 37.88? 141.96? 160.96? 77.88? 77.52? 8.26? 262.24? 128.9? 70.88? 3.76? 4.02? 61.96? 361.96? 16.74? 99.98? 8.56? 8.96? 11.62? 35.06? 330.4? 12.96? 3.96? 59.98? 11.68? 3.9? 801.96? 191.96? 5.96? 1,665.62? 25.16? 7.16? 3.52? 69.52? 47.3? 24.56? 44.46? 181.96? 141.96? 45.68? 5.04? 15.42? 360.38? 11.16? 41.96? 129.98? 32.54? 59.98? 198.46? 11.68? 16.9? 24.4? 241.96? 37.94? 273.96? 25.06? 801.96? 18.98? 476.8? 19.96? 6.28? 480.74? 85.3? 238.? 11.56? 8.56? 356.94? 659.9? 9.82? 30.28? 35.34? 14.56? 12.7? 13.48? 52.96? 97.88? 999.98? 7.04? 20.7? 12.94? 15.92? 13.96? 73.98? 22.58? 14.2? 12.96? 58.34? 56.3? 696.42? 51.98? 10.16? 14.76? 34.08? 6.56? 24.56? 37.94? 102.96? 209.7? 47.98? 323.1? 9.96? 11.36? 11.16? 16.78? 20.96? 167.86? 16.28? 99.54? 12.96? 111.96? 39.68? 11.68? 17.48? 71.88? 9.08? 5.78? 17.24? 55.98? 12.56? 43.96? 167.96? 12.96? 248.98? 43.32? 12.96? 12.96? 361.96? 37.3? 81.96? 269.98? 15.28? 11.96? 105.98? 325.86? 5.76? 127.96? 26.86? 8.26? 17.76? 7.9? 589.9? 24.88? 17.14? 47.3? 11.76? 69.98? 21.36? 142.36? 14.62? 11.68? 521.96? 61.96? 8.26? 29.84? 67.98? 61.06? 9.96? 7.9? 127.96? 37.94? 239.9? 10.36? 69.52? 22.58? 61.96? 27.58? 5.88? 1,793.98? 5.32? 3.36? 37.94? 4.2? 227.28? 61.96? 35.96? 231.98? 96.08? 3.62? 90.48? 14.88? 23.1? 5.68? 96.08? 4.36? 12.96? 85.9? 37.4? 8.4? 199.98? 12.9? 5.22? 10.56? 2,321.9? 20.46? 72.64? 33.48? 137.62? 33.9? 716.? 18.54? 699.98? 43.98? 391.98? 299.98? 99.98? 12.96? 601.3? 119.9? 86.26? 67.78? 301.96? 3.9? 37.68? 75.84? 23.16? 9.26? 105.98? 20.7? 17.48? 81.98? 59.98? 13.68? 10.56? 11.76? 85.52? 6.16? 4.08? 39.98? 64.96? 15.96? 6.68? 13.98? 8.? 15.78? 45.98? 81.96? 273.96? 9.82? 9.96? 71.98? 79.98? 15.36? 3.52? 331.96? 40.56? 68.46? 750.68? 36.? 40.68? 7.36? 6.56? 41.9? 8.96? 61.96? 160.32? 9.78? 37.94? 12.96? 25.16? 10.16? 6.16? 56.3? 6.56? 6.16? 352.38? 245.98? 391.98? 68.62? 7.78? 659.9? 843.9? 117.96? 201.96? 359.98? 6.16? 17.46? 10.56? 14.62? 12.96? 109.92? 12.96? 61.06? 25.16? 19.36? 19.3? 12.96? 5.56? 97.84? 77.52? 91.96? 238.62? 5.56? 581.96? 47.98? 715.64? 9.64? 301.96? 109.92? 11.16? 4.56? 28.28? 45.68? 25.06? 659.9? 110.96? 5.88? 262.24? 7.78? 81.98? 414.96? 360.38? 13.56? 32.06? 161.96? 19.86? 12.96? 77.56? 91.96? 17.34? 71.98? 69.98? 11.36? 270.62? 72.48? 212.8? 72.64? 13.76? 4.36? 1,299.66? 11.96? 3.76? 257.98? 22.96? 13.36? 3.52? 21.2? 838.38? 121.96? 63.96? 14.6? 96.08? 76.12? 191.98? 360.38? 13.98? 465.16? 311.98? 69.52? 701.96? 196.62? 15.96? 15.28? 66.58? 30.44? 69.28? 35.06? 337.98? 56.3? 119.02? 14.76? 10.56? 229.94? 12.96? 14.62? 5.76? 241.96? 21.96? 37.94? 10.76? 45.68? 56.56? 3.76? 261.96? 13.28? 131.98? 108.96? 139.92? 13.36? 11.96? 231.72? 191.96? 12.96? 79.78? 39.66? 113.92? 6.16? 17.? 29.84? 83.9? 3.6? 16.34? 23.32? 116.98? 121.96? 8.74? 61.96? 7.96? 81.96? 14.76? 12.76? 99.98? 9.96? 358.58? 32.48? 735.98? 33.96? 27.88? 44.96? 7.38? 12.96? 25.06? 411.98? 34.48? 41.28? 14.76? 115.96? 7.38? 2.48? 21.34? 12.96? 75.98? 6.46? 59.98? 11.96? 12.96? 25.76? 5.04? 32.96? 5.22? 36.? 12.96? 166.72? 124.36? 23.32? 83.42? 3.52? 42.76? 421.1? 25.98? 3.28? 7.76? 71.96? 61.96? 141.96? 27.46? 89.98? 141.96? 69.52? 19.54? 12.6? 11.96? 138.? 6.08? 17.46? 30.88? 465.16? 12.96? 24.14? 119.98? 5.56? 2,541.98? 41.96? 111.? 843.9? 5.76? 67.88? 257.98? 16.9? 378.? 99.98? 30.44? 12.96? 569.64? 52.76? 14.88? 261.74? 14.56? 609.98? 5.48? 391.98? 12.96? 6.08? 23.36? 362.92? 29.36? 5.76? 1,399.98? 70.88? 221.96? 41.94? 12.96? 9.54? 5.76? 18.54? 441.96? 106.96? 259.98? 341.96? 12.96? 1,199.98? 11.56? 11.68? 17.48? 6.58? 7.96? 450.04? 34.6? 33.02? 45.96? 25.06? 97.88? 40.48? 12.6? 159.98? 45.96? 9.96? 17.9? 81.96? 13.38? 6.16? 8.56? 97.82? 399.98? 6.24? 715.64? 38.62? 59.98? 23.36? 8.56? 6.24? 1.98? 271.9? 9.82? 11.76? 210.68? 33.18? 4.16? 12.96? 5.76? 12.96? 8.26? 41.96? 41.94? 11.96? 3.52? 10.68? 141.96? 32.48? 238.? 61.96? 227.96? 307.98? 999.98? 8.96? 549.98? 12.96? 82.64? 31.02? 40.68? 19.98? 299.9? 111.98? 180.96? 77.56? 8.74? 7.7? 20.56? 13.36? 76.12? 11.76? 27.46? 22.68? 39.98? 199.98? 40.48? 4.36? 129.3? 210.68? 7.5? 5.76? 19.98? 35.98? 20.7? 45.68? 110.96? 18.62? 97.82? 12.96? 23.? 3.64? 13.76? 9.82? 199.98? 32.54? 24.56? 607.52? 31.16? 11.88? 40.54? 23.18? 56.96? 13.96? 39.68? 7.38? 81.98? 7.3? 199.98? 118.? 22.66? 5.16? 231.72? 12.48? 3.52? 210.58? 133.98? 37.68? 27.96? 14.62? 12.96? 45.98? 221.98? 341.96? 40.48? 307.98? 16.56? 10.56? 386.34? 39.96? 89.9? 31.86? 276.28? 121.78? 25.06? 177.68? 159.98? 16.74? 8.56? 273.96? 5.76? 9.68? 7.38? 5.82? 99.98? 487.96? 1,793.98? 22.58? 10.86? 3.36? 21.96? 21.98? 23.08? 90.48? 24.56? 16.56? 5.56? 299.98? 41.9? 22.96? 8.28? 27.46? 159.98? 99.98? 101.96? 45.68? 31.96? 13.98? 24.56? 39.96? 39.88? 15.28? 5.56? 12.96? 9.64? 64.96? 14.56? 163.88? 6.56? 14.88? 13.36? 15.56? 41.96? 3.64? 18.54? 11.56? 37.94? 50.? 32.56? 12.96? 14.62? 701.96? 31.96? 12.96? 110.96? 99.98? 11.88? 111.96? 26.7? 93.02? 52.76? 33.48? 39.96? 1.98? 75.88? 11.76? 8.56? 11.56? 5.76? 137.54? 11.56? 64.96? 26.96? 12.96? 323.1? 12.96? 7.3? 3.62? 19.96? 18.96? 4.36? 20.12? 269.98? 310.12? 159.98? 8.26? 17.76? 292.1? 4.3? 81.96? 238.62? 9.84? 8.28? 129.3? 29.6? 5.76? 39.68? 12.56? 13.08? 24.56? 2.52? 18.76? 18.96? 6.36? 11.16? 159.98? 9.96? 20.62? 209.7? 12.96? 199.98? 17.38? 7.3? 735.98? 119.56? 13.36? 97.98? 91.96? 243.16? 114.9? 1,029.95? 32.4? 14.9? 171.55? 28.4? 149.95? 19.9? 622.45? 1,503.25? 32.4? 34.4? 179.95? 27.15? 714.3? 94.85? 14.7? 704.25? 449.15? 6,354.95? 2,999.95? 22.2? 979.95? 22.75? 32.4? 1,049.2? 459.95? 38.9? 33.4? 32.35? 1,298.55? 31.4? 149.95? 406.6? 32.4? 173.8? 520.05? 154.9? 24.1? 44.75? 32.4? 124.95? 601.65? 177.2? 14.4? 28.9? 279.9? 619.95? 63.9? 41.85? 14.9? 32.4? 114.2? 114.95? 579.3? 72.8? 13.05? 145.9? 912.75? 16.4? 158.9? 9.45? 14.75? 33.9? 29.7? 33.75? 124.75? 354.9? 979.95? 73.2? 523.25? 33.45? 10.4? 12.35? 19.9? 242.9? 454.9? 129.45? 14.7? 139.95? 215.65? 21.4? 831.2? 26.4? 141.4? 196.45? 99.2? 149.95? 11.65? 15.4? 244.55? 296.85? 24.9? 69.5? 1,394.95? 144.95? 199.95? 304.45? 104.9? 199.95? 80.3? 39.9? 94.85? 18.45? 324.9? 479.9? 17.45? 84.95? 3,999.95? 199.95? 44.75? 526.45? 44.4? 306.2? 16.4? 259.7? 390.75? 43.? 76.3? 41.7? 277.4? 63.2? 32.75? 37.? 56.45? 28.4? 24.2? 754.45? 595.? 345.? 95.1? 18.75? 32.4? 82.95? 1,137.75? 8,187.65? 114.2? 15.75? 526.45? 319.9? 18.45? 63.9? 14.4? 1,325.85? 14.4? 619.95? 15.7? 109.9? 13.9? 81.2? 14.45? 1,447.65? 48.4? 54.5? 145.85? 704.9? 114.6? 32.4? 23.85? 26.4? 49.65? 52.4? 41.4? 189.7? 43.7? 10.8? 449.15? 19.? 904.9? 504.9? 32.4? 13.9? 214.95? 57.75? 61.? 479.95? 135.9? 43.1? 395.? 32.4? 32.4? 78.35? 67.? 254.9? 53.2? 349.95? 94.85? 114.9? 56.45? 324.9? 4,164.05? 248.85? 51.75? 29.? 50.8? 1,287.45? 1,799.75? 29.9? 56.65? 34.95? 152.? 579.95? 655.9? 21.4? 54.9? 10.75? 20.65? 65.5? 277.4? 217.85? 142.4? 34.7? 32.4? 204.95? 23.55? 249.95? 33.4? 118.25? 28.4? 354.9? 87.6? 29.05? 1,458.65? 141.4? 34.95? 26.4? 48.9? 9.4? 74.? 1,424.9? 149.95? 41.95? 769.95? 345.? 193.8? 21.4? 29.9? 24.9? 204.85? 32.4? 404.9? 9,449.95? 629.95? 46.35? 24.7? 49.25? 1,604.9? 1,049.2? 20.9? 13.05? 25.3? 18.? 104.9? 51.75? 159.75? 303.25? 199.9? 971.5? 30.4? 34.75? 24.1? 965.85? 29.2? 32.4? 78.35? 169.45? 25.4? 244.55? 24.9? 21.4? 99.9? 36.4? 13.9? 8.8? 91.6? 77.55? 77.55? 140.75? 51.75? 64.4? 244.55? 166.45? 33.4? 279.9? 114.2? 269.9? 57.75? 1,325.85? 19.9? 14.4? 56.7? 69.5? 714.3? 687.4? 61.4? 14.7? 26.4? 21.4? 232.55? 17.05? 51.55? 39.9? 3,504.9? 397.6? 28.9? 35.4? 29.9? 8.4? 114.95? 249.95? 35.2? 406.6? 44.75? 68.95? 16.9? 244.55? 899.95? 39.9? 63.2? 224.75? 26.4? 1,649.95? 1,640.7? 249.95? 57.4? 86.2? 19.6? 84.55? 145.9? 67.4? 1,325.85? 2,999.95? 8.? 10.9? 11.05? 21.3? 1,040.8? 499.95? 152.8? 74.45? 32.4? 57.9? 154.9? 44.75? 26.4? 177.55? 619.95? 81.4? 74.95? 20.65? 83.7? 32.4? 304.9? 32.4? 1,133.35? 21.4? 26.4? 14.9? 25.4? 95.1? 25.9? 10.5? 676.55? 154.9? 429.9? 504.9? 14.9? 8.4? 54.9? 57.75? 272.4? 36.4? 44.75? 274.8? 354.9? 26.7? 629.95? 28.85? 22.45? 179.9? 24.75? 304.9? 704.25? 33.4? 19.05? 29.7? 24.55? 286.15? 311.15? 824.95? 477.15? 34.7? 24.9? 14.7? 37.2? 74.? 2,079.4? 629.95? 32.4? 279.9? 529.9? 8.8? 399.95? 291.1? 158.9? 419.9? 8.8? 469.95? 32.4? 4,164.05? 1,747.25? 356.85? 42.85? 87.4? 19.75? 149.95? 177.2? 629.95? 47.4? 35.4? 17.9? 168.1? 17,499.95? 152.65? 1,640.7? 67.9? 10.9? 32.4? 114.2? 244.55? 491.55? 28.4? 36.4? 10.2? 24.1? 24.85? 154.9? 24.1? 26.4? 226.2? 27.9? 33.9? 54.9? 51.55? 54.9? 16.45? 135.3? 111.15? 157.9? 15.6? 21.4? 756.8? 16.4? 354.9? 47.4? 14.7? 64.75? 979.95? 135.3? 400.8? 21.9? 29.9? 14.4? 149.95? 15.7? 34.4? 99.2? 46.9? 1,499.95? 25.9? 29.9? 214.9? 146.45? 194.7? 14.4? 53.9? 99.2? 154.9? 89.95? 1,779.9? 219.9? 32.4? 26.9? 154.9? 464.? 32.4? 343.85? 82.4? 3,404.5? 14.9? 72.9? 254.9? 89.95? 199.75? 1,323.9? 393.25? 892.35? 61.4? 61.1? 109.9? 234.95? 118.25? 204.95? 595.? 199.75? 474.95? 67.15? 169.45? 174.95? 1,649.95? 32.4? 44.75? 354.9? 498.? 32.4? 31.4? 24.3? 77.55? 111.15? 141.9? 174.95? 17.9? 2,154.9? 25.3? 83.7? 8,749.95? 1,454.9? 1,287.45? 168.1? 82.95? 90.? 174.95? 826.? 399.95? 5.7? 94.2? 49.5? 40.7? 17.9? 450.? 1,287.45? 73.2? 22.55? 1,294.75? 13.9? 15.75? 67.15? 99.2? 99.95? 204.85? 16.4? 12.3? 756.8? 104.75? 13.9? 19