In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\acer\OneDrive\Desktop\day12 dataset cleaned.csv")

In [3]:
df.shape

(9994, 9)

In [4]:
df.head()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
0,CA-2016-152156,CG-12520,11-Aug-16,42420,? 731.94,FUR-CH-10000454,3,0.0,? 219.582
1,CA-2015-106320,EB-13870,25-Sep-15,84057,"? 1,044.63",FUR-TA-10000577,3,0.0,? 240.2649
2,CA-2016-121755,EH-13945,16-Jan-16,90049,? 90.57,TEC-AC-10003027,3,0.0,? 11.7741
3,CA-2016-169194,LH-16900,20-Jun-16,19901,? 45.,TEC-AC-10002167,3,0.0,? 4.95
4,CA-2015-135545,KM-16720,24-Nov-15,90004,? 146.73,OFF-PA-10003892,3,0.0,? 68.9631

In [5]:
df.tail()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
9989,CA-2016-105781,JF-15565,16-Feb-16,10024,? 326.646,FUR-CH-10001802,3,0.10,? 39.9234
9990,CA-2017-144491,CJ-12010,27-Mar-17,77070,"? 1,023.332",FUR-BO-10001811,5,0.32,30.098 -?
9991,CA-2016-122581,JK-15370,21-Aug-16,10035,? 573.174,FUR-CH-10002961,7,0.10,? 63.686
9992,CA-2015-104948,KH-16510,13-Nov-15,92404,? 683.332,FUR-BO-10004357,4,0.15,40.196 -?
9993,CA-2015-168088,CM-12655,19-Mar-15,77041,? 383.4656,FUR-BO-10004218,4,0.32,67.6704 -?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Customer ID  9994 non-null   object
 2   Order Date   9994 non-null   object
 3   Postal Code  9994 non-null   int64
 4   Sales        9994 non-null   object
 5   Product ID   9994 non-null   object
 6   Quantity     9994 non-null   int64
 7   Discount     9994 non-null   float64
 8   Profit       9994 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 702.8+ KB

In [7]:
df.describe()

        Postal Code     Quantity     Discount
count   9994.000000  9994.000000  9994.000000
mean   55190.379428     3.789574     0.156203
std    32063.693350     2.225110     0.206452
min     1040.000000     1.000000     0.000000
25%    23223.000000     2.000000     0.000000
50%    56430.500000     3.000000     0.200000
75%    90008.000000     5.000000     0.200000
max    99301.000000    14.000000     0.800000